on_epoch_end_calls:
  _target_: dgn.callbacks.OnEpochEndCalls
  callbacks:
    - _target_: dgn.callbacks.Log
    - _target_: dgn.callbacks.HistoryPlot
      log_every_n_epochs: 10
    - _target_: dgn.callbacks.SaveAsH5
      log_every_n_epochs: 10
      ground_truth:
          - 'inp'